export default function Head() {
  return (
    <>
      <title>Dev Clubhouse</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name="description"
        content="website to give hot takes or controversial opinion on the tech industry"
      ></meta>
      <link rel="icon" href="/favicon.png" />
    </>
  )
}
